### ISSUE TITLE
CarliniWagnerL2Attack takes forever on CIFAR10

### ISSUE THREAD

**Issue by dvd42** [BorealisAI/advertorch#83]
Thanks for this great toolbox!! :) 

I am trying to use this attack to perturb a model. I am just calling it with the default parameters, and it seems to take forever:

![image](https://user-images.githubusercontent.com/22733646/91164057-c4586400-e6ce-11ea-9c30-4759cdfde417.png)

Is this expected behaviour?

**Comment by aaa6237** [comment]
I am having the same problem but on CIFAR100.

**Comment by gwding** [comment]
Hi there, I believe for CIFAR10 the speed issue is kind of unavoidable. because carlini attack does need many many iterations and in the original paper, the authors only test on the first 1000 images "We evaluate on the first 1, 000 images in the test set on
CIFAR and MNSIT." in https://arxiv.org/pdf/1608.04644.pdf

However, if you like there might be some problems to make it "problematically slow", I would suggest compare single iteration run time with PGD attack.

If speed the main concern in your application, I would recommend using DDN https://github.com/BorealisAI/advertorch/blob/master/advertorch/attacks/decoupled_direction_norm.py or FAB attack https://github.com/BorealisAI/advertorch/blob/master/advertorch/attacks/fast_adaptive_boundary.py

**Comment by dvd42** [comment]
Thank you for the reply, I will be closing the issue as this does seems to be expected behaviour.
