### ISSUE TITLE
How to use BPDA to attack the adversarial trained model

### ISSUE THREAD

**Issue by rshaojimmy** [BorealisAI/advertorch#98]
Hi,

Given a model (defenseNet) trained with adversarial training based on PGD attack, I want to use the BPDA to attack and evaluate this model with provided BPDAWrapper.

1. First I use the following code:

from advertorch.attacks import PGDAttack
from advertorch.bpda import BPDAWrapper

attacker = BPDAWrapper(defenseNet, forwardsub=defenseNet)
adversary = PGDAttack(attacker)

bpda_adv = adversary.perturb(clean_data, true_label)
bpda_adv_defended = defense(bpda_adv)

Results based on the above codes are always close to the white-box PGD attack test with defenseNet.

2. Then I use the following code:

def _identity(x):
    return x

attacker = BPDAWrapper(defenseNet, forwardsub=_identity)
adversary = PGDAttack(attacker)

The following error reports:
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([64, 6]) and output[0] has a shape of torch.Size([64, 3, 32, 32]).

Seems forwardsub just directly outputs the input images with shape of torch.Size([64, 3, 32, 32]).

May I ask which way is correct and how to use the BPDA to attack and evaluate this model with provided BPDAWrapper?

Thanks so much.

**Comment by gwding** [comment]
Hi,

BPDA is for bypassing gradient obfuscating layer as described in the original paper https://arxiv.org/abs/1802.00420

For 1, this is expected behavior, as you use defenseNet as forward and defenseNet's backward as backward. so it's equivalent as using defenseNet itself without using BPDA

For 2, this is also expected. BPDA was designed to work with something like a image denoising layer, whose input and output have the same shape.

hope this helps.

**Comment by rshaojimmy** [comment]
Thanks for your reply!

So if I would like to use BPDA to attack an adversarially trained model with the provided BPDAWrapper, what should I do?

Thanks.

**Comment by gwding** [comment]
If there's no "gradient obfuscating" component in the model, then BPDA would not be useful for attacking.

**Comment by rshaojimmy** [comment]
I see. Thanks so much!
